// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_bgmCompare_parallel
Rcpp::List run_bgmCompare_parallel(arma::imat observations, const int num_groups, Rcpp::List num_obs_categories, Rcpp::List sufficient_blume_capel, Rcpp::List sufficient_pairwise, const arma::ivec& num_categories, const double main_alpha, const double main_beta, const double pairwise_scale, const double difference_scale, const double difference_selection_alpha, const double difference_selection_beta, const std::string difference_prior, const int iter, const int burnin, const bool na_impute, const arma::imat& missing_data_indices, const arma::uvec& is_ordinal_variable, const arma::ivec& baseline_category, const bool difference_selection, const arma::imat main_effect_indices, const arma::imat pairwise_effect_indices, const double target_accept, const int nuts_max_depth, const bool learn_mass_matrix, const arma::mat projection, const arma::ivec& group_membership, const arma::imat& group_indices, const arma::imat& interaction_index_matrix, const arma::mat& inclusion_probability, const int num_chains, const int nThreads);
RcppExport SEXP _bgms_run_bgmCompare_parallel(SEXP observationsSEXP, SEXP num_groupsSEXP, SEXP num_obs_categoriesSEXP, SEXP sufficient_blume_capelSEXP, SEXP sufficient_pairwiseSEXP, SEXP num_categoriesSEXP, SEXP main_alphaSEXP, SEXP main_betaSEXP, SEXP pairwise_scaleSEXP, SEXP difference_scaleSEXP, SEXP difference_selection_alphaSEXP, SEXP difference_selection_betaSEXP, SEXP difference_priorSEXP, SEXP iterSEXP, SEXP burninSEXP, SEXP na_imputeSEXP, SEXP missing_data_indicesSEXP, SEXP is_ordinal_variableSEXP, SEXP baseline_categorySEXP, SEXP difference_selectionSEXP, SEXP main_effect_indicesSEXP, SEXP pairwise_effect_indicesSEXP, SEXP target_acceptSEXP, SEXP nuts_max_depthSEXP, SEXP learn_mass_matrixSEXP, SEXP projectionSEXP, SEXP group_membershipSEXP, SEXP group_indicesSEXP, SEXP interaction_index_matrixSEXP, SEXP inclusion_probabilitySEXP, SEXP num_chainsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< const int >::type num_groups(num_groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type num_obs_categories(num_obs_categoriesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type sufficient_blume_capel(sufficient_blume_capelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type sufficient_pairwise(sufficient_pairwiseSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< const double >::type main_alpha(main_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type main_beta(main_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type pairwise_scale(pairwise_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type difference_scale(difference_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type difference_selection_alpha(difference_selection_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type difference_selection_beta(difference_selection_betaSEXP);
    Rcpp::traits::input_parameter< const std::string >::type difference_prior(difference_priorSEXP);
    Rcpp::traits::input_parameter< const int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type missing_data_indices(missing_data_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type is_ordinal_variable(is_ordinal_variableSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type baseline_category(baseline_categorySEXP);
    Rcpp::traits::input_parameter< const bool >::type difference_selection(difference_selectionSEXP);
    Rcpp::traits::input_parameter< const arma::imat >::type main_effect_indices(main_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::imat >::type pairwise_effect_indices(pairwise_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< const int >::type nuts_max_depth(nuts_max_depthSEXP);
    Rcpp::traits::input_parameter< const bool >::type learn_mass_matrix(learn_mass_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type projection(projectionSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_membership(group_membershipSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type group_indices(group_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type interaction_index_matrix(interaction_index_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type inclusion_probability(inclusion_probabilitySEXP);
    Rcpp::traits::input_parameter< const int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_bgmCompare_parallel(observations, num_groups, num_obs_categories, sufficient_blume_capel, sufficient_pairwise, num_categories, main_alpha, main_beta, pairwise_scale, difference_scale, difference_selection_alpha, difference_selection_beta, difference_prior, iter, burnin, na_impute, missing_data_indices, is_ordinal_variable, baseline_category, difference_selection, main_effect_indices, pairwise_effect_indices, target_accept, nuts_max_depth, learn_mass_matrix, projection, group_membership, group_indices, interaction_index_matrix, inclusion_probability, num_chains, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// run_gibbs_sampler_for_bgmCompare
Rcpp::List run_gibbs_sampler_for_bgmCompare(int chain_id, arma::imat observations, const int num_groups, Rcpp::List num_obs_categories, Rcpp::List sufficient_blume_capel, Rcpp::List sufficient_pairwise, const arma::ivec& num_categories, const double main_alpha, const double main_beta, const double pairwise_scale, const double difference_scale, const double difference_selection_alpha, const double difference_selection_beta, const std::string difference_prior, const int iter, const int burnin, const bool na_impute, const arma::imat& missing_data_indices, const arma::uvec& is_ordinal_variable, const arma::ivec& baseline_category, const bool difference_selection, const arma::imat main_effect_indices, const arma::imat pairwise_effect_indices, const double target_accept, const int nuts_max_depth, const bool learn_mass_matrix, const arma::mat projection, const arma::ivec& group_membership, const arma::imat& group_indices, const arma::imat& interaction_index_matrix, arma::mat inclusion_probability);
RcppExport SEXP _bgms_run_gibbs_sampler_for_bgmCompare(SEXP chain_idSEXP, SEXP observationsSEXP, SEXP num_groupsSEXP, SEXP num_obs_categoriesSEXP, SEXP sufficient_blume_capelSEXP, SEXP sufficient_pairwiseSEXP, SEXP num_categoriesSEXP, SEXP main_alphaSEXP, SEXP main_betaSEXP, SEXP pairwise_scaleSEXP, SEXP difference_scaleSEXP, SEXP difference_selection_alphaSEXP, SEXP difference_selection_betaSEXP, SEXP difference_priorSEXP, SEXP iterSEXP, SEXP burninSEXP, SEXP na_imputeSEXP, SEXP missing_data_indicesSEXP, SEXP is_ordinal_variableSEXP, SEXP baseline_categorySEXP, SEXP difference_selectionSEXP, SEXP main_effect_indicesSEXP, SEXP pairwise_effect_indicesSEXP, SEXP target_acceptSEXP, SEXP nuts_max_depthSEXP, SEXP learn_mass_matrixSEXP, SEXP projectionSEXP, SEXP group_membershipSEXP, SEXP group_indicesSEXP, SEXP interaction_index_matrixSEXP, SEXP inclusion_probabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chain_id(chain_idSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< const int >::type num_groups(num_groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type num_obs_categories(num_obs_categoriesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type sufficient_blume_capel(sufficient_blume_capelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type sufficient_pairwise(sufficient_pairwiseSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< const double >::type main_alpha(main_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type main_beta(main_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type pairwise_scale(pairwise_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type difference_scale(difference_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type difference_selection_alpha(difference_selection_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type difference_selection_beta(difference_selection_betaSEXP);
    Rcpp::traits::input_parameter< const std::string >::type difference_prior(difference_priorSEXP);
    Rcpp::traits::input_parameter< const int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type missing_data_indices(missing_data_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type is_ordinal_variable(is_ordinal_variableSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type baseline_category(baseline_categorySEXP);
    Rcpp::traits::input_parameter< const bool >::type difference_selection(difference_selectionSEXP);
    Rcpp::traits::input_parameter< const arma::imat >::type main_effect_indices(main_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::imat >::type pairwise_effect_indices(pairwise_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< const int >::type nuts_max_depth(nuts_max_depthSEXP);
    Rcpp::traits::input_parameter< const bool >::type learn_mass_matrix(learn_mass_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type projection(projectionSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_membership(group_membershipSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type group_indices(group_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type interaction_index_matrix(interaction_index_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inclusion_probability(inclusion_probabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(run_gibbs_sampler_for_bgmCompare(chain_id, observations, num_groups, num_obs_categories, sufficient_blume_capel, sufficient_pairwise, num_categories, main_alpha, main_beta, pairwise_scale, difference_scale, difference_selection_alpha, difference_selection_beta, difference_prior, iter, burnin, na_impute, missing_data_indices, is_ordinal_variable, baseline_category, difference_selection, main_effect_indices, pairwise_effect_indices, target_accept, nuts_max_depth, learn_mass_matrix, projection, group_membership, group_indices, interaction_index_matrix, inclusion_probability));
    return rcpp_result_gen;
END_RCPP
}
// run_bgm_parallel
Rcpp::List run_bgm_parallel(const arma::imat& observations, const arma::ivec& num_categories, const double interaction_scale, const std::string& edge_prior, const arma::mat& inclusion_probability, const double beta_bernoulli_alpha, const double beta_bernoulli_beta, const double dirichlet_alpha, const double lambda, const arma::imat& interaction_index_matrix, const int iter, const int burnin, const arma::imat& num_obs_categories, const arma::imat& sufficient_blume_capel, const double threshold_alpha, const double threshold_beta, const bool na_impute, const arma::imat& missing_index, const arma::uvec& is_ordinal_variable, const arma::ivec& reference_category, const bool edge_selection, const std::string& update_method, const arma::imat& pairwise_effect_indices, const double target_accept, const arma::imat& sufficient_pairwise, const int hmc_num_leapfrogs, const int nuts_max_depth, const bool learn_mass_matrix, const int num_chains, const int nThreads);
RcppExport SEXP _bgms_run_bgm_parallel(SEXP observationsSEXP, SEXP num_categoriesSEXP, SEXP interaction_scaleSEXP, SEXP edge_priorSEXP, SEXP inclusion_probabilitySEXP, SEXP beta_bernoulli_alphaSEXP, SEXP beta_bernoulli_betaSEXP, SEXP dirichlet_alphaSEXP, SEXP lambdaSEXP, SEXP interaction_index_matrixSEXP, SEXP iterSEXP, SEXP burninSEXP, SEXP num_obs_categoriesSEXP, SEXP sufficient_blume_capelSEXP, SEXP threshold_alphaSEXP, SEXP threshold_betaSEXP, SEXP na_imputeSEXP, SEXP missing_indexSEXP, SEXP is_ordinal_variableSEXP, SEXP reference_categorySEXP, SEXP edge_selectionSEXP, SEXP update_methodSEXP, SEXP pairwise_effect_indicesSEXP, SEXP target_acceptSEXP, SEXP sufficient_pairwiseSEXP, SEXP hmc_num_leapfrogsSEXP, SEXP nuts_max_depthSEXP, SEXP learn_mass_matrixSEXP, SEXP num_chainsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< const double >::type interaction_scale(interaction_scaleSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type edge_prior(edge_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type inclusion_probability(inclusion_probabilitySEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_alpha(beta_bernoulli_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_beta(beta_bernoulli_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type dirichlet_alpha(dirichlet_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type interaction_index_matrix(interaction_index_matrixSEXP);
    Rcpp::traits::input_parameter< const int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type num_obs_categories(num_obs_categoriesSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type sufficient_blume_capel(sufficient_blume_capelSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold_alpha(threshold_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold_beta(threshold_betaSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type missing_index(missing_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type is_ordinal_variable(is_ordinal_variableSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type reference_category(reference_categorySEXP);
    Rcpp::traits::input_parameter< const bool >::type edge_selection(edge_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type update_method(update_methodSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type pairwise_effect_indices(pairwise_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type sufficient_pairwise(sufficient_pairwiseSEXP);
    Rcpp::traits::input_parameter< const int >::type hmc_num_leapfrogs(hmc_num_leapfrogsSEXP);
    Rcpp::traits::input_parameter< const int >::type nuts_max_depth(nuts_max_depthSEXP);
    Rcpp::traits::input_parameter< const bool >::type learn_mass_matrix(learn_mass_matrixSEXP);
    Rcpp::traits::input_parameter< const int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_bgm_parallel(observations, num_categories, interaction_scale, edge_prior, inclusion_probability, beta_bernoulli_alpha, beta_bernoulli_beta, dirichlet_alpha, lambda, interaction_index_matrix, iter, burnin, num_obs_categories, sufficient_blume_capel, threshold_alpha, threshold_beta, na_impute, missing_index, is_ordinal_variable, reference_category, edge_selection, update_method, pairwise_effect_indices, target_accept, sufficient_pairwise, hmc_num_leapfrogs, nuts_max_depth, learn_mass_matrix, num_chains, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// run_gibbs_sampler_for_bgm
Rcpp::List run_gibbs_sampler_for_bgm(int chain_id, arma::imat observations, const arma::ivec& num_categories, const double interaction_scale, const std::string& edge_prior, arma::mat inclusion_probability, const double beta_bernoulli_alpha, const double beta_bernoulli_beta, const double dirichlet_alpha, const double lambda, const arma::imat& interaction_index_matrix, const int iter, const int burnin, arma::imat num_obs_categories, arma::imat sufficient_blume_capel, const double threshold_alpha, const double threshold_beta, const bool na_impute, const arma::imat& missing_index, const arma::uvec& is_ordinal_variable, const arma::ivec& reference_category, bool edge_selection, const std::string& update_method, const arma::imat pairwise_effect_indices, const double target_accept, arma::imat sufficient_pairwise, const int hmc_num_leapfrogs, const int nuts_max_depth, const bool learn_mass_matrix);
RcppExport SEXP _bgms_run_gibbs_sampler_for_bgm(SEXP chain_idSEXP, SEXP observationsSEXP, SEXP num_categoriesSEXP, SEXP interaction_scaleSEXP, SEXP edge_priorSEXP, SEXP inclusion_probabilitySEXP, SEXP beta_bernoulli_alphaSEXP, SEXP beta_bernoulli_betaSEXP, SEXP dirichlet_alphaSEXP, SEXP lambdaSEXP, SEXP interaction_index_matrixSEXP, SEXP iterSEXP, SEXP burninSEXP, SEXP num_obs_categoriesSEXP, SEXP sufficient_blume_capelSEXP, SEXP threshold_alphaSEXP, SEXP threshold_betaSEXP, SEXP na_imputeSEXP, SEXP missing_indexSEXP, SEXP is_ordinal_variableSEXP, SEXP reference_categorySEXP, SEXP edge_selectionSEXP, SEXP update_methodSEXP, SEXP pairwise_effect_indicesSEXP, SEXP target_acceptSEXP, SEXP sufficient_pairwiseSEXP, SEXP hmc_num_leapfrogsSEXP, SEXP nuts_max_depthSEXP, SEXP learn_mass_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chain_id(chain_idSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< const double >::type interaction_scale(interaction_scaleSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type edge_prior(edge_priorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inclusion_probability(inclusion_probabilitySEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_alpha(beta_bernoulli_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_beta(beta_bernoulli_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type dirichlet_alpha(dirichlet_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type interaction_index_matrix(interaction_index_matrixSEXP);
    Rcpp::traits::input_parameter< const int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type num_obs_categories(num_obs_categoriesSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type sufficient_blume_capel(sufficient_blume_capelSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold_alpha(threshold_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold_beta(threshold_betaSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type missing_index(missing_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type is_ordinal_variable(is_ordinal_variableSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type reference_category(reference_categorySEXP);
    Rcpp::traits::input_parameter< bool >::type edge_selection(edge_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type update_method(update_methodSEXP);
    Rcpp::traits::input_parameter< const arma::imat >::type pairwise_effect_indices(pairwise_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type sufficient_pairwise(sufficient_pairwiseSEXP);
    Rcpp::traits::input_parameter< const int >::type hmc_num_leapfrogs(hmc_num_leapfrogsSEXP);
    Rcpp::traits::input_parameter< const int >::type nuts_max_depth(nuts_max_depthSEXP);
    Rcpp::traits::input_parameter< const bool >::type learn_mass_matrix(learn_mass_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(run_gibbs_sampler_for_bgm(chain_id, observations, num_categories, interaction_scale, edge_prior, inclusion_probability, beta_bernoulli_alpha, beta_bernoulli_beta, dirichlet_alpha, lambda, interaction_index_matrix, iter, burnin, num_obs_categories, sufficient_blume_capel, threshold_alpha, threshold_beta, na_impute, missing_index, is_ordinal_variable, reference_category, edge_selection, update_method, pairwise_effect_indices, target_accept, sufficient_pairwise, hmc_num_leapfrogs, nuts_max_depth, learn_mass_matrix));
    return rcpp_result_gen;
END_RCPP
}
// sample_omrf_gibbs
IntegerMatrix sample_omrf_gibbs(int no_states, int no_variables, IntegerVector no_categories, NumericMatrix interactions, NumericMatrix thresholds, int iter);
RcppExport SEXP _bgms_sample_omrf_gibbs(SEXP no_statesSEXP, SEXP no_variablesSEXP, SEXP no_categoriesSEXP, SEXP interactionsSEXP, SEXP thresholdsSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type no_states(no_statesSEXP);
    Rcpp::traits::input_parameter< int >::type no_variables(no_variablesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type no_categories(no_categoriesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type interactions(interactionsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type thresholds(thresholdsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_omrf_gibbs(no_states, no_variables, no_categories, interactions, thresholds, iter));
    return rcpp_result_gen;
END_RCPP
}
// sample_bcomrf_gibbs
IntegerMatrix sample_bcomrf_gibbs(int no_states, int no_variables, IntegerVector no_categories, NumericMatrix interactions, NumericMatrix thresholds, StringVector variable_type, IntegerVector reference_category, int iter);
RcppExport SEXP _bgms_sample_bcomrf_gibbs(SEXP no_statesSEXP, SEXP no_variablesSEXP, SEXP no_categoriesSEXP, SEXP interactionsSEXP, SEXP thresholdsSEXP, SEXP variable_typeSEXP, SEXP reference_categorySEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type no_states(no_statesSEXP);
    Rcpp::traits::input_parameter< int >::type no_variables(no_variablesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type no_categories(no_categoriesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type interactions(interactionsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type thresholds(thresholdsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type variable_type(variable_typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type reference_category(reference_categorySEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_bcomrf_gibbs(no_states, no_variables, no_categories, interactions, thresholds, variable_type, reference_category, iter));
    return rcpp_result_gen;
END_RCPP
}
// compare_anova_gibbs_sampler
List compare_anova_gibbs_sampler(arma::imat& observations, const arma::imat& main_effect_indices, const arma::imat& pairwise_effect_indices, const arma::mat& projection, const arma::imat& num_categories, const int num_groups, const arma::imat& group_indices, const double interaction_scale, const double pairwise_difference_scale, const double main_difference_scale, const String& pairwise_difference_prior, const String& main_difference_prior, arma::mat& inclusion_probability_difference, const double pairwise_beta_bernoulli_alpha, const double pairwise_beta_bernoulli_beta, const double main_beta_bernoulli_alpha, const double main_beta_bernoulli_beta, const arma::imat& Index, const int iter, const int burnin, List& num_obs_categories, List& sufficient_blume_capel, const double prior_threshold_alpha, const double prior_threshold_beta, const bool na_impute, const arma::imat& missing_data_indices, const arma::uvec& is_ordinal_variable, const arma::ivec& baseline_category, const bool independent_thresholds, const bool save_main, const bool save_pairwise, const bool save_indicator, const bool display_progress, bool difference_selection);
RcppExport SEXP _bgms_compare_anova_gibbs_sampler(SEXP observationsSEXP, SEXP main_effect_indicesSEXP, SEXP pairwise_effect_indicesSEXP, SEXP projectionSEXP, SEXP num_categoriesSEXP, SEXP num_groupsSEXP, SEXP group_indicesSEXP, SEXP interaction_scaleSEXP, SEXP pairwise_difference_scaleSEXP, SEXP main_difference_scaleSEXP, SEXP pairwise_difference_priorSEXP, SEXP main_difference_priorSEXP, SEXP inclusion_probability_differenceSEXP, SEXP pairwise_beta_bernoulli_alphaSEXP, SEXP pairwise_beta_bernoulli_betaSEXP, SEXP main_beta_bernoulli_alphaSEXP, SEXP main_beta_bernoulli_betaSEXP, SEXP IndexSEXP, SEXP iterSEXP, SEXP burninSEXP, SEXP num_obs_categoriesSEXP, SEXP sufficient_blume_capelSEXP, SEXP prior_threshold_alphaSEXP, SEXP prior_threshold_betaSEXP, SEXP na_imputeSEXP, SEXP missing_data_indicesSEXP, SEXP is_ordinal_variableSEXP, SEXP baseline_categorySEXP, SEXP independent_thresholdsSEXP, SEXP save_mainSEXP, SEXP save_pairwiseSEXP, SEXP save_indicatorSEXP, SEXP display_progressSEXP, SEXP difference_selectionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat& >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type main_effect_indices(main_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type pairwise_effect_indices(pairwise_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type projection(projectionSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< const int >::type num_groups(num_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type group_indices(group_indicesSEXP);
    Rcpp::traits::input_parameter< const double >::type interaction_scale(interaction_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type pairwise_difference_scale(pairwise_difference_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type main_difference_scale(main_difference_scaleSEXP);
    Rcpp::traits::input_parameter< const String& >::type pairwise_difference_prior(pairwise_difference_priorSEXP);
    Rcpp::traits::input_parameter< const String& >::type main_difference_prior(main_difference_priorSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type inclusion_probability_difference(inclusion_probability_differenceSEXP);
    Rcpp::traits::input_parameter< const double >::type pairwise_beta_bernoulli_alpha(pairwise_beta_bernoulli_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type pairwise_beta_bernoulli_beta(pairwise_beta_bernoulli_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type main_beta_bernoulli_alpha(main_beta_bernoulli_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type main_beta_bernoulli_beta(main_beta_bernoulli_betaSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type Index(IndexSEXP);
    Rcpp::traits::input_parameter< const int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< List& >::type num_obs_categories(num_obs_categoriesSEXP);
    Rcpp::traits::input_parameter< List& >::type sufficient_blume_capel(sufficient_blume_capelSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_threshold_alpha(prior_threshold_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_threshold_beta(prior_threshold_betaSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type missing_data_indices(missing_data_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type is_ordinal_variable(is_ordinal_variableSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type baseline_category(baseline_categorySEXP);
    Rcpp::traits::input_parameter< const bool >::type independent_thresholds(independent_thresholdsSEXP);
    Rcpp::traits::input_parameter< const bool >::type save_main(save_mainSEXP);
    Rcpp::traits::input_parameter< const bool >::type save_pairwise(save_pairwiseSEXP);
    Rcpp::traits::input_parameter< const bool >::type save_indicator(save_indicatorSEXP);
    Rcpp::traits::input_parameter< const bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< bool >::type difference_selection(difference_selectionSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_anova_gibbs_sampler(observations, main_effect_indices, pairwise_effect_indices, projection, num_categories, num_groups, group_indices, interaction_scale, pairwise_difference_scale, main_difference_scale, pairwise_difference_prior, main_difference_prior, inclusion_probability_difference, pairwise_beta_bernoulli_alpha, pairwise_beta_bernoulli_beta, main_beta_bernoulli_alpha, main_beta_bernoulli_beta, Index, iter, burnin, num_obs_categories, sufficient_blume_capel, prior_threshold_alpha, prior_threshold_beta, na_impute, missing_data_indices, is_ordinal_variable, baseline_category, independent_thresholds, save_main, save_pairwise, save_indicator, display_progress, difference_selection));
    return rcpp_result_gen;
END_RCPP
}
// compute_Vn_mfm_sbm
arma::vec compute_Vn_mfm_sbm(arma::uword no_variables, double dirichlet_alpha, arma::uword t_max, double lambda);
RcppExport SEXP _bgms_compute_Vn_mfm_sbm(SEXP no_variablesSEXP, SEXP dirichlet_alphaSEXP, SEXP t_maxSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type no_variables(no_variablesSEXP);
    Rcpp::traits::input_parameter< double >::type dirichlet_alpha(dirichlet_alphaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Vn_mfm_sbm(no_variables, dirichlet_alpha, t_max, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bgms_run_bgmCompare_parallel", (DL_FUNC) &_bgms_run_bgmCompare_parallel, 32},
    {"_bgms_run_gibbs_sampler_for_bgmCompare", (DL_FUNC) &_bgms_run_gibbs_sampler_for_bgmCompare, 31},
    {"_bgms_run_bgm_parallel", (DL_FUNC) &_bgms_run_bgm_parallel, 30},
    {"_bgms_run_gibbs_sampler_for_bgm", (DL_FUNC) &_bgms_run_gibbs_sampler_for_bgm, 29},
    {"_bgms_sample_omrf_gibbs", (DL_FUNC) &_bgms_sample_omrf_gibbs, 6},
    {"_bgms_sample_bcomrf_gibbs", (DL_FUNC) &_bgms_sample_bcomrf_gibbs, 8},
    {"_bgms_compare_anova_gibbs_sampler", (DL_FUNC) &_bgms_compare_anova_gibbs_sampler, 34},
    {"_bgms_compute_Vn_mfm_sbm", (DL_FUNC) &_bgms_compute_Vn_mfm_sbm, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bgms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
