# ------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED - DO NOT EDIT
# Generated by configure
# To add C++ code, place .cpp files anywhere under src/
# ------------------------------------------------------------------
SOURCES = \
  RcppExports.cpp \
  bgm/bgm_helper.cpp \
  bgm/bgm_logp_and_grad.cpp \
  bgm/bgm_sampler.cpp \
  bgmCompare/bgmCompare_helper.cpp \
  bgmCompare/bgmCompare_logp_and_grad.cpp \
  bgmCompare/bgmCompare_sampler.cpp \
  bgmCompare_interface.cpp \
  bgm_interface.cpp \
  data_simulation.cpp \
  math/custom_exp.cpp \
  math/e_exp.cpp \
  mcmc/mcmc_hmc.cpp \
  mcmc/mcmc_leapfrog.cpp \
  mcmc/mcmc_nuts.cpp \
  mcmc/mcmc_rwm.cpp \
  mcmc/mcmc_utils.cpp \
  priors/sbm_edge_prior.cpp \
  sbm_edge_prior_interface.cpp \
  utils/progress_manager.cpp \

